import type { Metadata } from "next";
import { Inter, Public_Sans, Coming_Soon } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/components/auth/SessionProvider";
import { StorageListener } from "@/components/event-listeners";

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})
export const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const comingSoon = Coming_Soon({
  weight: "400",
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <SessionProvider>
          <StorageListener/>
          {children}
          <div id="modal-root"></div>
        </SessionProvider>
      </body>
    </html>
  );
}
